### ISSUE TITLE
Seems to be broken on 1.19.3 Spigot 

### ISSUE THREAD

**Issue by Tanza3D** [MajekDev/PartyChat#134]
**Describe the bug**
Hello! For a while now, this plugin has been my go-to for party chats, as I run servers with alot of people who build and we need to split our chats apart for less congestion and confusion. Recently, we set up a new server on 1.19.3, and the server is throwing an error when starting. Running any command also throws an error.

When starting, it says this (both when running a latest manual build, and a release build):
```
[15:59:27] [Server thread/ERROR]: Error occurred while enabling PartyChat v4.2.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/builder/AbstractBuilder
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:193) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at dev.majek.pc.chat.ChatParser.getBuilderFromString(ChatParser.java:304) ~[?:?]
        at dev.majek.pc.chat.ChatParser.parse(ChatParser.java:172) ~[?:?]
        at dev.majek.pc.chat.ChatParser.parse(ChatParser.java:186) ~[?:?]
        at dev.majek.pc.chat.MessageHandler.sendFormattedMessage(MessageHandler.java:50) ~[?:?]
        at dev.majek.pc.PartyChat.onEnable(PartyChat.java:189) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:587) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.builder.AbstractBuilder
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 24 more
```
        
And, when running a command, it throws this error:
```
org.bukkit.command.CommandException: Unhandled exception executing command 'pc' in plugin PartyChat v4.2.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:847) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:306) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:290) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1957) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1919) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1154) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1133) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1110) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1021) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3663-Spigot-a2190e3-b56426c]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Error finding value for path prefix in en_US.yml, did you delete something?
        at dev.majek.pc.data.DataHandler.getConfigString(DataHandler.java:358) ~[?:?]
        at dev.majek.pc.chat.MessageHandler.sendMessageWithReplacement(MessageHandler.java:106) ~[?:?]
        at dev.majek.pc.command.PartyChatCommand.onCommand(PartyChatCommand.java:331) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

![image](https://user-images.githubusercontent.com/33783503/222450474-405a72ee-7dbc-4d00-a194-97844f436221.png)
The file "en_US.yml" is there.

![image](https://user-images.githubusercontent.com/33783503/222450824-ac747d8b-26db-4da9-ad65-fb3b77eacfaf.png)

**Software (please complete the following information):**
 - Server Implementation: Spigot
 - Minecraft Version 1.19.3
 - Java Version 19
 - Plugin Version: 4.2.1 / 4.2.2
 
 I've tried manually building the latest commit, but the error persists. the V5 branch seems to be older than the latest, so I suspect a similar issue would exist there. A fix for this, or a pointer in the right direction so I can attempt a fix myself, would be highly appreciated! Thanks!

**Comment by Majekdor** [comment]
Are you opposed to using Paper instead of Spigot? It tends to be better in general but it would probably also serve as a temporary fix for the issue. According to my metrics most people use PartyChat on Paper or Purpur on Minecraft 1.19.2+.

**Comment by Majekdor** [comment]
I will still look into the issue when I have time, I'm just slammed with college and work right now so I don't know when that will be. Obviously this plugin hasn't been getting the attention it deserves.

**Comment by Tanza3D** [comment]
> Are you opposed to using Paper instead of Spigot? It tends to be better in general but it would probably also serve as a temporary fix for the issue. According to my metrics most people use PartyChat on Paper or Purpur on Minecraft 1.19.2+.

For whatever reason, the world I'm using is extremely fragile, and when using paper alot of chunks get corrupted. I have no clue why but the easiest option so far other than possibly moving all the chunks into a new world file was just to use Spigot, which seems to load it fine.
