### ISSUE TITLE
[Bug] Plugin disables if it can't check for updates

### ISSUE THREAD

**Issue by untuned** [MajekDev/PartyChat#136]
**Describe the bug**
If SpigotMC's API is down (the entire site gives a 502 as of this post), the plugin does not enable.

**To Reproduce**
1. Turn off internet access to the Minecraft server
2. Boot the server with PartyChat

**Expected behavior**
The plugin fails to check for updates, but still boots without issues.

**Software (please complete the following information):**
 - Server Implementation: Purpur
 - Minecraft Version: 1.19.3
 - Java Version: 17
 - Plugin Version: 4.2.1

**Additional context**
Error message in console:
```
[18:19:20 INFO]: [PCv4] Cannot look for updates: Server returned HTTP response code: 502 for URL: https://api.spigotmc.org/simple/0.1/index.php?action=getResource&id=79295
[18:19:20 ERROR]: Error occurred while enabling PartyChat v4.2.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because the return value of "dev.majek.pc.util.UpdateChecker.getSpigotVersion()" is null
        at dev.majek.pc.util.UpdateChecker.<init>(UpdateChecker.java:57) ~[PartyChat-4.2.1.jar:?]
        at dev.majek.pc.PartyChat.onEnable(PartyChat.java:179) ~[PartyChat-4.2.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:574) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:485) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:19:20 INFO]: [PCv4] Disabling PartyChat v4.2.1
```

**Comment by Majekdor** [comment]
Well that's just terrible programming by me now isn't it ._. will fix this week if not today
